CREATE TABLE IF NOT EXISTS address (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(50),
    city VARCHAR(50),
    street VARCHAR(100),
    house VARCHAR(5),
    flat VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS delivery (
    delivery_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    from_address_id BIGINT REFERENCES address(address_id),
    to_address_id BIGINT REFERENCES address(address_id),
    order_id UUID,
    delivery_state VARCHAR(15)
);